Repository wr1159/advent, pull requests merged in 2023-05, with the labels that each got.

#5 Added tailwindcss prettier config
  README.md
  components/Navbar.tsx
  package.json
  yarn.lock
Labels: effort:low

#7 Feature/routing pages
  app/(auth)/auth/page.tsx
  app/(dashboard)/dashboard/layout.tsx
  app/(dashboard)/dashboard/page.tsx
  app/(dashboard)/dashboard/statistics/page.tsx
  app/(public)/documentation/page.tsx
  app/(public)/layout.tsx
  app/(public)/orbital/page.tsx
  app/(public)/page.tsx
  app/layout.tsx
  components/Navbar.tsx
Labels: effort:medium

#9 Fixed mobile display for several pages
  components/Card.tsx
  components/Features.tsx
  components/Hero.tsx
  components/HeroChild.tsx
  components/Navbar.tsx
  tailwind.config.js
Labels: effort:low

#10 Hotfix for Navbar
  components/Navbar.tsx
Labels: bug, effort:low

#11 Hotfix for Navbar
  components/Navbar.tsx
Labels: bug, effort:low

#12 Refactor NavBar and Other Small Fixes
  app/(public)/orbital/page.tsx
  app/(public)/page.tsx
  components/Hero.tsx
  components/MobileNav.tsx
  components/Navbar.tsx
  components/OrbitalRow.tsx
Labels: bug, enhancement, effort:low

#13 Add Footer Component
  app/(dashboard)/dashboard/layout.tsx
  app/(public)/layout.tsx
  app/(public)/orbital/page.tsx
  components/Footer.tsx
  components/Hero.tsx
Labels: enhancement, effort:low

#15 Basic Dashboard Frontend Page
  app/(dashboard)/dashboard/page.tsx
  components/EventItem.tsx
  components/EventOperations.tsx
  package.json
  yarn.lock
Labels: enhancement, effort:medium

#14 Feature/user auth
  .env
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(dashboard)/dashboard/page.tsx
  components/LogOut.tsx
  components/LoginForm.tsx
  components/Navbar.tsx
  components/SignUpForm.tsx
  firebaseconfig.js
  next.config.js
  package.json
  utils/google-ver.ts
  utils/signin.ts
  utils/signup.ts
  yarn.lock
Labels: enhancement, effort:high

#35 Speed up CI/CD Pipeline
  .github/workflows/pr-pipeline.yaml
Labels: enhancement, effort:low

#34 Minor changes: Orbital Content, Decrease Hero Whitespace, Responsive Footer
  app/(public)/orbital/page.tsx
  components/Footer.tsx
  components/Hero.tsx
Labels: bug, effort:low

#33 Add Charts in Statistics Page
  app/(dashboard)/dashboard/statistics/page.tsx
  components/Chart.tsx
  components/Charts/BarChart.tsx
  components/Charts/LineChart.tsx
  package.json
  yarn.lock
Labels: enhancement, effort:medium

#38 Feature/create template
  app/(auth)/auth/page.tsx
  app/(auth)/login/page.tsx
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(dashboard)/dashboard/layout.tsx
  app/(dashboard)/dashboard/page.tsx
  app/(event)/event/[userId]/[eventId]/page.tsx
  components/Button.tsx
  components/CreateEventForm.tsx
  components/EventItem.tsx
  components/EventOperations.tsx
  components/HeroChild.tsx
  components/LoginForm.tsx
  components/Navbar.tsx
  components/SaveTemplate.tsx
  components/__tests__/EventItem.test.tsx
  database.drawio.pdf
  firebaseconfig.js
  package.json
  utils/add-attendee.ts
  utils/event-query.ts
  utils/getUser.ts
  utils/queryTemplate.ts
  utils/save-template.ts
  yarn.lock
Labels: effort:high

#42 Update activity diagram in README
  README.md
  app/(public)/orbital/page.tsx
  components/MDX/MilestoneOne.mdx
Labels: documentation
