Repository wr1159/advent, pull requests merged in 2023-06, with the labels that each got.

#55 Table of Content for MDX
  mdx-components.tsx
Labels: enhancement, effort:low

#53 Change redirection from auth to login
  components/HeroChild.tsx
Labels: bug

#54 Implement Picking Colour for Background and Text
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(event)/event/[userId]/[eventId]/page.tsx
  utils/save-template.ts
Labels: enhancement, effort:low

#64 Fix event sorting
  app/(dashboard)/dashboard/page.tsx
  components/CreateEventForm.tsx
  package.json
  yarn.lock
Labels: bug, effort:low

#66 WYSIWYG editor + iframe
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(event)/event/[userId]/[eventId]/page.tsx
  components/Button.tsx
  components/Editor/EditorRightColumn.tsx
  components/Editor/WYSIWYGContainer.tsx
  next.config.mjs
  package.json
  utils/save-template.ts
  yarn.lock
Labels: enhancement, effort:high

#67 Features for form editor and preview page.
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(event)/event/[userId]/[eventId]/page.tsx
  components/Editor/Editor_Side/AttendeeFormEditor.tsx
  components/Editor/Editor_Side/EditorRightColumn.tsx
  components/Editor/Editor_Side/ImageUpload.tsx
  components/Editor/Editor_Side/TimeSlotInsertion.tsx
  components/Editor/Preview_Side/DataPage.tsx
  components/Editor/Preview_Side/FormWrapper.tsx
  components/Editor/Preview_Side/PaymentPage.tsx
  components/Editor/Preview_Side/PreviewForm.tsx
  components/Editor/Preview_Side/TimeSlotSelectionPage.tsx
  next.config.mjs
  package.json
  utils/add-attendee.ts
  utils/retrieveImage.ts
  utils/save-template.ts
  utils/uploadImage.ts
  utils/useMultistepForm.ts
  yarn.lock
Labels: effort:high

#68 Show data in a table
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(dashboard)/dashboard/page.tsx
  app/(dashboard)/dashboard/statistics/[userId]/[eventId]/page.tsx
  app/(dashboard)/dashboard/statistics/page.tsx
  components/Attendee/AttendeeTable.tsx
  components/Chart.tsx
  components/Charts/BarChart.tsx
  components/Charts/LineChart.tsx
  components/CreateEventForm.tsx
  components/Editor/Editor_Side/AttendeeFormEditor.tsx
  components/Editor/Preview_Side/PreviewForm.tsx
  package.json
  types/PageProps.ts
  utils/add-attendee.ts
  utils/event-query.ts
  utils/queryAttendees.ts
  utils/queryTemplate.ts
  yarn.lock
Labels: enhancement, effort:medium

#69 Testing existing components and functions
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  components/CreateEventForm.tsx
  components/Editor/Editor_Side/AttendeeFormEditor.tsx
  components/Editor/Editor_Side/EditorRightColumn.tsx
  components/Editor/Editor_Side/ImageUpload.tsx
  components/Editor/Editor_Side/TimeSlotInsertion.tsx
  components/Editor/Preview_Side/DataPage.tsx
  components/Editor/Preview_Side/FormWrapper.tsx
  components/Editor/Preview_Side/PaymentPage.tsx
  components/Editor/Preview_Side/PreviewForm.tsx
  components/Editor/Preview_Side/TimeSlotSelectionPage.tsx
  components/SaveTemplate.tsx
  components/__tests__/CreateEventForm.test.tsx
  components/__tests__/Editor/Editor_Side/AttendeeFormEditor.test.tsx
  components/__tests__/Editor/Editor_Side/EditorRightColumn.test.tsx
  components/__tests__/Editor/Editor_Side/ImageUpload.test.tsx
  components/__tests__/Editor/Preview_Side/DataPage.test.tsx
  components/__tests__/Editor/Preview_Side/FormWrapper.test.tsx
  components/__tests__/Editor/Preview_Side/PreviewForm.test.tsx
  components/__tests__/EventOperations.test.tsx
  components/__tests__/LoginForm.test.tsx
  components/__tests__/SignUpForm.test.tsx
  firebaseconfig.js
  package-lock.json
  package.json
  utils/__tests__/event-query.test.ts
  utils/__tests__/getUser.test.ts
  utils/__tests__/queryTemplate.test.ts
  utils/__tests__/retrieveImage.test.ts
  utils/__tests__/save-template.test.ts
  utils/__tests__/uploadImage.test.ts
  utils/event-query.ts
  utils/google-ver.ts
  utils/save-template.ts
  yarn.lock
Labels: effort:medium

#72 Update MS2 Project log
  app/(public)/orbital/project-log/page.tsx
  components/MDX/NathanProjectLog.mdx
  components/MDX/WRProjectLog.mdx
Labels: documentation, effort:low
