Repository wr1159/advent, pull requests merged in 2023-07, with the labels that each got.

#74 Add charts
  app/(dashboard)/dashboard/statistics/[userId]/[eventId]/page.tsx
  components/Attendee/AttendeeTable.tsx
  components/Chart.tsx
  components/Charts/BarChart.tsx
  components/Charts/LineChart.tsx
  components/Dropdown.tsx
  components/Editor/Editor_Side/AttendeeFormEditor.tsx
  components/__tests__/AttendeeTable.test.tsx
  components/__tests__/Chart.test.tsx
  components/__tests__/Charts/BarChart.tsx
  components/__tests__/Charts/LineChart.tsx
  components/__tests__/Dropdown.test.tsx
  package.json
  types/Attendant.ts
  utils/__tests__/capitalizeLetter.test.ts
  utils/capitalizeLetter.ts
  yarn.lock
Labels: effort:medium

#76 User walkthrough tutorial for editor page.
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(dashboard)/dashboard/page.tsx
  components/Button.tsx
  components/Editor/Editor_Side/AttendeeFormEditor.tsx
  components/Editor/Editor_Side/EditorRightColumn.tsx
  components/Editor/Editor_Side/ImageUpload.tsx
  components/Editor/WYSIWYGContainer.tsx
  components/Navbar.tsx
  components/__tests__/Editor/Editor_Side/AttendeeFormEditor.test.tsx
  components/__tests__/Editor/Editor_Side/EditorRightColumn.test.tsx
  package.json
  utils/walkthroughSteps.ts
  yarn.lock
Labels: enhancement, effort:medium

#79 Payment system implementation
  .env
  app/(dashboard)/dashboard/editor/[userId]/[eventId]/page.tsx
  app/(event)/event/[userId]/[eventId]/awaitPayment/page.jsx
  app/(event)/event/[userId]/[eventId]/page.tsx
  app/api/getproducts/route.ts
  app/api/payment/route.tsx
  app/success/page.tsx
  components/Editor/Editor_Side/AttendeeFormEditor.tsx
  components/Editor/Editor_Side/EditorRightColumn.tsx
  components/Editor/Preview_Side/DataPage.tsx
  components/Editor/Preview_Side/FormWrapper.tsx
  components/Editor/Preview_Side/PreviewForm.tsx
  components/Editor/WYSIWYGContainer.tsx
  components/__tests__/Editor/Preview_Side/PreviewForm.test.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement, effort:high

#81 Exclude certain attributes
  app/(dashboard)/dashboard/statistics/[userId]/[eventId]/page.tsx
Labels: bug
